baseurl = "/"
languageCode = "en-US"
title = "Tien Angel Nguyen"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "angel(1).jpg"
  author = "Tien Angel Nguyen"
  description = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "angelxnguyen"
  Email         = "anguyen0107@gmail.com"
  Twitter       = "angelxnguyen"

## Main Menu
[[menu.main]]
  name = "blogs"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "About Me!"
  identifier = "resume"
  weight = 300
  url = "/resume/"

